import { createClient } from '@supabase/supabase-js'
import * as fs from 'fs'
import * as path from 'path'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
const supabase = createClient(supabaseUrl, supabaseKey)

const jobs = [
  {
    source_id: 'adzuna',
    external_id: 'adz-001',
    title: 'Senior Software Engineer',
    company: 'Flutterwave',
    location: 'Lagos, Nigeria',
    is_remote: false,
    description: 'We are looking for a Senior Software Engineer to join our payments team. You will build and maintain scalable payment infrastructure processing millions of transactions daily.',
    salary_min: 80000,
    salary_max: 120000,
    currency: 'USD',
    job_type: 'full_time',
    seniority: 'Senior',
    apply_url: 'https://flutterwave.com/careers/senior-software-engineer',
    ats_platform: 'greenhouse',
    auto_apply_eligible: true,
    posted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    dedupe_hash: 'hash-001',
    match_score: 92,
  },
  {
    source_id: 'jooble',
    external_id: 'joo-001',
    title: 'Frontend Developer (React)',
    company: 'Paystack',
    location: 'Lagos, Nigeria',
    is_remote: true,
    description: 'Join our frontend team to build beautiful, performant interfaces for Africa\'s leading payment platform. You\'ll work closely with design and backend teams.',
    salary_min: 60000,
    salary_max: 90000,
    currency: 'USD',
    job_type: 'full_time',
    seniority: 'Mid',
    apply_url: 'https://paystack.com/careers/frontend-developer',
    ats_platform: 'lever',
    auto_apply_eligible: true,
    posted_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    dedupe_hash: 'hash-002',
    match_score: 85,
  },
  {
    source_id: 'linkedin_unofficial',
    external_id: 'li-001',
    title: 'Product Manager',
    company: 'Andela',
    location: 'Remote',
    is_remote: true,
    description: 'Andela is seeking a Product Manager to drive our talent marketplace platform. You will define product strategy, prioritize features, and work with engineering to deliver.',
    salary_min: 70000,
    salary_max: 110000,
    currency: 'USD',
    job_type: 'full_time',
    seniority: 'Senior',
    apply_url: 'https://www.linkedin.com/jobs/view/product-manager-andela',
    ats_platform: null,
    auto_apply_eligible: false,
    posted_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    dedupe_hash: 'hash-003',
    match_score: 78,
  },
  {
    source_id: 'adzuna',
    external_id: 'adz-002',
    title: 'DevOps Engineer',
    company: 'Interswitch',
    location: 'Lagos, Nigeria',
    is_remote: false,
    description: 'Manage and improve our cloud infrastructure on AWS. You will automate deployments, manage Kubernetes clusters, and ensure 99.99% uptime for our payment systems.',
    salary_min: 75000,
    salary_max: 100000,
    currency: 'USD',
    job_type: 'full_time',
    seniority: 'Senior',
    apply_url: 'https://interswitch.com/careers/devops-engineer',
    ats_platform: 'workable',
    auto_apply_eligible: true,
    posted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    dedupe_hash: 'hash-004',
    match_score: 70,
  },
  {
    source_id: 'jooble',
    external_id: 'joo-002',
    title: 'Data Scientist',
    company: 'Kuda Bank',
    location: 'Lagos, Nigeria',
    is_remote: true,
    description: 'Help us build the future of digital banking in Africa. As a Data Scientist, you will analyze user behavior, build recommendation systems, and optimize our credit risk models.',
    salary_min: 65000,
    salary_max: 95000,
    currency: 'USD',
    job_type: 'full_time',
    seniority: 'Mid',
    apply_url: 'https://kuda.com/careers/data-scientist',
    ats_platform: 'greenhouse',
    auto_apply_eligible: true,
    posted_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    dedupe_hash: 'hash-005',
    match_score: 65,
  },
  {
    source_id: 'linkedin_unofficial',
    external_id: 'li-002',
    title: 'UI/UX Designer',
    company: 'Chipper Cash',
    location: 'Accra, Ghana',
    is_remote: true,
    description: 'Design intuitive, delightful experiences for millions of users across Africa. You will own the design process from research through high-fidelity mockups.',
    salary_min: 55000,
    salary_max: 85000,
    currency: 'USD',
    job_type: 'full_time',
    seniority: 'Mid',
    apply_url: 'https://www.linkedin.com/jobs/view/ui-ux-designer-chipper-cash',
    ats_platform: null,
    auto_apply_eligible: false,
    posted_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    dedupe_hash: 'hash-006',
    match_score: 88,
  },
  {
    source_id: 'adzuna',
    external_id: 'adz-003',
    title: 'Backend Engineer (Node.js)',
    company: 'PiggyVest',
    location: 'Lagos, Nigeria',
    is_remote: true,
    description: 'Build and maintain the backend services powering Nigeria\'s largest savings and investment platform. Experience with Node.js, PostgreSQL, and Redis required.',
    salary_min: 50000,
    salary_max: 80000,
    currency: 'USD',
    job_type: 'full_time',
    seniority: 'Mid',
    apply_url: 'https://piggyvest.com/careers/backend-engineer',
    ats_platform: 'lever',
    auto_apply_eligible: true,
    posted_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    dedupe_hash: 'hash-007',
    match_score: 90,
  },
  {
    source_id: 'jooble',
    external_id: 'joo-003',
    title: 'Mobile Developer (Flutter)',
    company: 'Carbon',
    location: 'Lagos, Nigeria',
    is_remote: false,
    description: 'Develop and maintain our cross-platform mobile application used by millions. You should have strong Flutter/Dart skills and experience with financial applications.',
    salary_min: 45000,
    salary_max: 75000,
    currency: 'USD',
    job_type: 'full_time',
    seniority: 'Mid',
    apply_url: 'https://carbon.ng/careers/mobile-developer',
    ats_platform: 'workable',
    auto_apply_eligible: true,
    posted_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    dedupe_hash: 'hash-008',
    match_score: 82,
  },
  {
    source_id: 'linkedin_unofficial',
    external_id: 'li-003',
    title: 'Technical Writer',
    company: 'Twilio',
    location: 'Remote',
    is_remote: true,
    description: 'Create clear, comprehensive documentation for Twilio\'s developer products. Strong technical background and excellent writing skills required.',
    salary_min: 60000,
    salary_max: 90000,
    currency: 'USD',
    job_type: 'full_time',
    seniority: 'Senior',
    apply_url: 'https://www.linkedin.com/jobs/view/technical-writer-twilio',
    ats_platform: null,
    auto_apply_eligible: false,
    posted_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    dedupe_hash: 'hash-009',
    match_score: 72,
  },
  {
    source_id: 'adzuna',
    external_id: 'adz-004',
    title: 'Customer Success Manager',
    company: 'Paystack',
    location: 'Lagos, Nigeria',
    is_remote: false,
    description: 'Help merchants succeed on Paystack. You will onboard new businesses, provide ongoing support, and identify opportunities for growth.',
    salary_min: 40000,
    salary_max: 60000,
    currency: 'USD',
    job_type: 'full_time',
    seniority: 'Mid',
    apply_url: 'https://paystack.com/careers/customer-success-manager',
    ats_platform: 'lever',
    auto_apply_eligible: false,
    posted_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    dedupe_hash: 'hash-010',
    match_score: 60,
  },
]

async function seed() {
  console.log('Seeding jobs...')
  const { data, error } = await supabase.from('jobs').upsert(jobs, {
    onConflict: 'source_id, external_id',
    ignoreDuplicates: false,
  })
  if (error) {
    console.error('Error seeding jobs:', error)
    process.exit(1)
  }
  console.log(`Seeded ${jobs.length} jobs successfully`)
}

seed()
